### ISSUE TITLE
Image Optimization on Custom Images

### ISSUE THREAD

**Issue by quantacode** [jonhare/DifferentiableSketching#5]
Hi,

How do I create an init.pdf for custom images (other than vancouver.jpg) to be used for "image optimization" experiment?

**Comment by jonhare** [comment]
init.pdf is just a pdf of the initial random starting point - it is created by the code when you run it (you can just remove that command line flag and argument if you don't want to save it). The only thing you need to change is the input image to get it working on a different image.
